/**
 * Plant Disease Detection - Trained Disease Class Labels
 * Auto-generated by train.py based on master pathology list.
 */
const PLANT_CLASSES = [
  "Alfalfa Mosaic",
  "Anthracnose",
  "Apple Scab",
  "Bacterial Canker",
  "Bacterial Leaf Spot",
  "Bacterial Soft Rot",
  "Bacterial Wilt",
  "Black Rot",
  "Black Spot",
  "Botrytis Bunch Rot",
  "Citrus Canker",
  "Clubroot",
  "Crown Gall",
  "Cucumber Mosaic",
  "Curly Top",
  "Damping-Off",
  "Downy Mildew",
  "Early Blight",
  "Fire Blight",
  "Fusarium Wilt",
  "Late Blight",
  "Leaf Curl",
  "Phytophthora Blight",
  "Plum Pox",
  "Potato Leafroll",
  "Powdery Mildew",
  "Pythium Root Rot",
  "Rhizoctonia Root Rot",
  "Rust",
  "Sooty Mold",
  "Tobacco Mosaic",
  "Tomato Spotted Wilt",
  "Verticillium Wilt",
  "Healthy Leaf"
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = { PLANT_CLASSES };
}
